service:
  name: kratos-base-project.adminInterface.service
  version: v1
  administrator:
    endpoint: discovery:///kratos-base-project.administrator.service
  goods:
    endpoint: discovery:///kratos-base-project.goods.service
trace:
  endpoint: http://124.222.172.237:14268/api/traces
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
auth:
  service_key: "kratos-base-project-admin-service-key"
  api_key: "kratos-base-project-admin-api-key"
consul:
  address: 124.222.172.237:8500
  scheme: http
